/*
 * Copyright (c) 2019
 * Created at 5/20/19 10:26 PM
 * Created by oktoprima
 * Email octoprima93@gmail.com
 * Github https://github.com/oktopriima
 */

package model

import (
	"time"
)

type Users struct {
	ID                int64     `json:"id"`
	Name              string    `json:"name"`
	AutogeneratedName bool      `json:"autogenerated_name"`
	Email             string    `json:"email"`
	Password          string    `json:"-"`
	IsResetPassword   bool      `json:"is_reset_password"`
	Phone             string    `json:"phone"`
	IsVerified        bool      `json:"is_verified"`
	Gcm               string    `json:"gcm"`
	RememberToken     *string   `json:"remember_token"`
	LastLogin         time.Time `json:"last_login"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	SecondaryEmail    string    `json:"secondary_email"`
	Avatar            string    `json:"avatar"`
	DeviceType        string    `json:"device_type"`
	HasPassword       bool      `json:"has_password"`
}
