/*
 * Copyright (c) 2019
 * Created at 5/20/19 10:26 PM
 * Created by oktoprima
 * Email octoprima93@gmail.com
 * Github https://github.com/oktopriima
 */

package services

import (
	"encoding/json"

	"github.com/oktopriima/mark-i/domain/model"
	"github.com/oktopriima/mark-i/domain/repository"
	"github.com/jinzhu/gorm"
)

type userServices struct {
	db *gorm.DB
}

func NewUserServices(db *gorm.DB) repository.UserRepository {
	return &userServices{db}
}

func (srv *userServices) Create(users *model.Users) (m *model.Users, err error) {
	db := srv.db.Create(&users)
	if err = db.Error; err != nil {
		return
	}

	byteData, err := json.Marshal(db.Value)
	if err != nil {
		return
	}
	if err = json.Unmarshal(byteData, &m); err != nil {
		return
	}

	return
}

func (srv *userServices) Update(users *model.Users) (err error) {
	err = srv.db.Save(&users).Error
	return
}

func (srv *userServices) Find(ID int64) (*model.Users, error) {
	m := new(model.Users)
	row := srv.db.Table("users").Select("*").Where("id = ?", ID).Row()
	err := row.Scan(&m.ID, &m.Name, &m.AutogeneratedName, &m.Email, &m.Password, &m.IsResetPassword, &m.Phone,
		&m.IsVerified, &m.Gcm, &m.RememberToken, &m.LastLogin, &m.CreatedAt, &m.UpdatedAt, &m.SecondaryEmail, &m.Avatar,
		&m.DeviceType, &m.HasPassword)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (srv *userServices) FindOneBy(criteria map[string]interface{}) (*model.Users, error) {
	m := new(model.Users)
	row := srv.db.Table("users").Select("*").Where(criteria).Row()
	if err := row.Scan(&m.ID, &m.Name, &m.AutogeneratedName, &m.Email, &m.Password, &m.IsResetPassword, &m.Phone,
		&m.IsVerified, &m.Gcm, &m.RememberToken, &m.LastLogin, &m.CreatedAt, &m.UpdatedAt, &m.SecondaryEmail, &m.Avatar,
		&m.DeviceType, &m.HasPassword); err != nil {
		return nil, err
	}
	return m, nil
}
