/*
 * Copyright (c) 2019
 * Created at 5/28/19 10:27 AM
 * Created by oktoprima
 * Email octoprima93@gmail.com
 * Github https://github.com/oktopriima
 */

package auth

import (
	"time"

	"github.com/oktopriima/mark-i/app/config"
	"github.com/oktopriima/mark-i/domain/model"
	"github.com/oktopriima/mark-i/libraries/helper"
	"github.com/oktopriima/mark-i/libraries/middleware"
	"github.com/pkg/errors"
	"golang.org/x/crypto/bcrypt"
)

func (uc *authUsecase) FacebookLogin(request AuthRequest) (AuthResponse, error) {
	fResp, err := helper.GetFacebookData(request.GetSocialToken())
	if err != nil {
		return nil, err
	}

	/** get user */
	user, err := uc.getUserByEmail(fResp.Email)
	if err != nil || user.ID == 0 {
		user, err := uc.registerFromFacebook(fResp)
		if err != nil {
			return nil, err
		}

		if _, err = uc.registerSocialMedia(user, fResp.ID, request); err != nil {
			return nil, err
		}
	}

	social, err := uc.getUserSocial(fResp.ID)
	if err != nil {
		return nil, err
	}

	if social.UserID != user.ID {
		return nil, errors.New("user didn't match")
	}

	/** generate parameter for Custom JWT */
	param := middleware.TokenStructure{}
	param.UserID = user.ID
	param.Email = user.Email
	param.Role = "consumer"

	auth := middleware.NewCustomAuth([]byte(config.SIGNATURE))
	token, err := auth.GenerateToken(param)
	if err != nil {
		return nil, err
	}

	if err = uc.updateLastLogin(user); err != nil {
		return nil, err
	}

	return token, nil
}

func (uc *authUsecase) registerFromFacebook(response *helper.FacebookResponse) (*model.Users, error) {
	pass, _ := bcrypt.GenerateFromPassword([]byte(helper.RandString(10)), bcrypt.DefaultCost)

	m := new(model.Users)

	m.Name = response.Name
	m.AutogeneratedName = true
	m.Email = response.Name
	m.Password = string(pass)
	m.IsResetPassword = false
	m.Phone = ""
	m.IsVerified = false
	m.Gcm = ""
	m.RememberToken = new(string)
	m.LastLogin = time.Now()
	m.CreatedAt = time.Now()
	m.UpdatedAt = time.Now()
	m.SecondaryEmail = response.Email
	m.Avatar = response.Avatar
	m.DeviceType = ""
	m.HasPassword = true

	if m, err := uc.userRepo.Create(m); err != nil {
		return nil, err
	} else {
		return m, nil
	}
}
